version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "jst-jobs-api-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresssql/data
  api:
    build: .
    container_name: "jst-jobs-search"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "DB"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
      SSL_MODE: "disable"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack
volumes:
  database_postgres: {}
networks:
  fullstack:
    driver: bridge
